# ==========================
# Website Configuration
# ==========================

WEBSITE_NAME = "E2M Solutions"

WEBSITE_URL = "https://www.e2msolutions.com"

# Crawl depth
MAX_PAGES = 350

# ==========================
# Local Knowledge Base
# ==========================

# JSON file generated by crawler
CACHE_FILE = "website_content.json"

# ==========================
# Retrieval Configuration
# ==========================

# Number of most relevant pages
TOP_K = 8

# Maximum characters taken from each page
MAX_PAGE_CHARS = 4000